AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the NewRelic::CloudFormation::Tagging resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: go1.x
      CodeUri: bin/
      Environment:
        Variables:
          LOG_LEVEL: info

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: go1.x
      CodeUri: bin/
      Environment: 
        Variables: 
          MODE: Test

  LiveTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: go1.x
      CodeUri: bin/
      Environment:
        Variables:
          LOG_LEVEL: trace
          TypeConfigurationFile: TypeConfigurationLive.json